apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drivex-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: drivex.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drivex-api
                port: { number: 80 }
